title: Home
views:
  - !include lovelace/views/default_view.yaml
  - !include lovelace/views/maintenance.yaml
  - !include lovelace/views/rooms.yaml
  - !include lovelace/views/sensors.yaml
  - !include lovelace/views/living_room_dashboard.yaml
  - !include lovelace/views/living_room_climate.yaml


button_card_templates: !include lovelace/button_card_templates.yaml