custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: Living Room Tablet
      config:
        footer_mode: true
        split_mode: true
  header_text: >-
    <style>
    #flip {height:24px;overflow:hidden;}
    #flip > div > div {color:#fff;height:24px;margin-bottom:24px;display:inline-block;}
    #flip div:first-child {animation: show 10s linear infinite;}
    .time { font-weight: bold; float: left; padding-right: 16px;}
    @keyframes show {
      0% {margin-top:-144px;}
      5% {margin-top:-96px;}
      33% {margin-top:-96px;}
      38% {margin-top:-48px;}
      66% {margin-top:-48px;}
      76% {margin-top:0px;}
      100% {margin-top:0px;}
    }
    #flipper p {position:fixed;color:#999; }
    </style>
    <div id=flipper>
    <span class=time>{{hours12}}:{{minutesLZ}} {{ampm}}</span>
    <div id=flip>
    <div><div>{{states('sensor.dark_sky_daily_summary')}}</div></div>
    <div><div>{{states('sensor.dark_sky_hourly_summary')}}</div></div>
    <div><div>{{states('sensor.dark_sky_summary')}} {{states.weather.dark_sky.attributes.temperature}}°</div></div>
    <div><div>{{states('sensor.dark_sky_hourly_summary')}}</div></div>
    </div></div>

title: Home
views:
  - !include lovelace/views/default_view.yaml
  - !include lovelace/views/maintenance.yaml
  - !include lovelace/views/rooms.yaml
  - !include lovelace/views/sensors.yaml
  - !include lovelace/views/living_room_dashboard.yaml
  - !include lovelace/views/living_room_climate.yaml


button_card_templates: !include lovelace/button_card_templates.yaml