- alias: Holiday Lights - On at Sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.garage_greenwave_port_1_switch
      - switch.garage_greenwave_port_2_switch
      - switch.garage_greenwave_port_3_switch

- alias: Holiday Lights - On in Morning
  trigger:
    - platform: time
      at: "06:40:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.garage_greenwave_port_1_switch
      - switch.garage_greenwave_port_2_switch
      - switch.garage_greenwave_port_3_switch