- alias: Holiday Lights - On at Sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.holiday_lights_port1
      - switch.holiday_lights_port2
      - switch.holiday_lights_port3

- alias: Holiday Lights - On in Morning
  trigger:
    - platform: time
      at: "06:40:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.holiday_lights_port1
      - switch.holiday_lights_port2
      - switch.holiday_lights_port3