- alias: Guest Bathroom Auto Lights (Day)
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.aeotec_multisensor_6_sensor_10_0
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:00:00'
        after: '5:00:00'
      - condition: state
        entity_id: light.guest_bathroom_vanity_light_level_7_0
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.guest_bathroom_fan_light_level_9_0
  - service: script.turn_off
    entity_id: script.guest_bathroom_light_day
  - service: homeassistant.turn_on
    entity_id: script.guest_bathroom_light_day