- alias: Porch Light Arrival
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.front_porch