# Automatically reboot wall tablets on a schedule
- alias: Wall Tablet Scheduled Reboot
  trigger:
    - platform: time
      at: "01:00:00"

  condition:
    - condition: time
      weekday:
        - mon
        - wed
        - fri
        - sat

  action:
    - service: button.press
      entity_id:
        - button.living_room_kiosk_restart_device
        - button.master_bedroom_kiosk_restart_device
        - button.nursery_kiosk_restart_device
        - button.zoeys_room_kiosk_restart_device