# Turn off outside lights if they are turned on during the day
- alias: Watchdog - Outside Lights
  trigger:
    - platform: time
      minutes: '/10'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: group.outdoor_lights
        state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.outdoor_lights