sensor:
  - platform: template
    sensors:
      front_door_battery:
        value_template: "{{ states.zwave.front_door.attributes.battery_level|default(-1)|int if states.zwave.front_door is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.front_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
          
      back_door_battery:
        value_template: "{{ states.zwave.back_door.attributes.battery_level|default(-1)|int if states.zwave.back_door is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.back_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
      
      garage_inside_door_battery:
        value_template: "{{ states.zwave.garage_inside_door.attributes.battery_level|default(-1)|int if states.zwave.garage_inside_door is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.garage_inside_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
          
      garage_side_door_battery:
        value_template: "{{ states.zwave.garage_side_door.attributes.battery_level|default(-1)|int if states.zwave.garage_side_door is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.garage_side_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
          
      hallway_smoke_battery:
        value_template: "{{ states.zwave.hallway_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.hallway_smoke_detector is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.hallway_smoke_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
          
      garage_smoke_battery:
        value_template: "{{ states.zwave.garage_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.garage_smoke_detector is not none }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.garage_smoke_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}