sensor:
  - platform: template
    sensors:
      front_door_battery:
        value_template: "{{ states.zwave.front_door.attributes.battery_level|default(-1)|int if states.zwave.front_door is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      back_door_battery:
        value_template: "{{ states.zwave.back_door.attributes.battery_level|default(-1)|int if states.zwave.back_door is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      garage_inside_door_battery:
        value_template: "{{ states.zwave.garage_inside_door.attributes.battery_level|default(-1)|int if states.zwave.garage_inside_door is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      garage_side_door_battery:
        value_template: "{{ states.zwave.garage_side_door.attributes.battery_level|default(-1)|int if states.zwave.garage_side_door is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      hallway_smoke_battery:
        value_template: "{{ states.zwave.hallway_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.hallway_smoke_detector is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      garage_smoke_battery:
        value_template: "{{ states.zwave.garage_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.garage_smoke_detector is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      nursery_smoke_battery:
        value_template: "{{ states.zwave.nursery_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.nursery_smoke_detector is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      office_smoke_battery:
        value_template: "{{ states.zwave.office_smoke_detector.attributes.battery_level|default(-1)|int if states.zwave.office_smoke_detector is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      living_room_multisensor_battery:
        value_template: "{{ states.zwave.living_room_multisensor.attributes.battery_level|default(-1)|int if states.zwave.living_room_multisensor is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      guest_bathroom_multisensor_battery:
        value_template: "{{ states.zwave.guest_bathroom_multisensor.attributes.battery_level|default(-1)|int if states.zwave.guest_bathroom_multisensor is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      kitchen_window_battery:
        value_template: "{{ states.zwave.kitchen_window.attributes.battery_level|default(-1)|int if states.zwave.kitchen_window is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      office_window_battery:
        value_template: "{{ states.zwave.office_window.attributes.battery_level|default(-1)|int if states.zwave.office_window is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      nursery_window_battery:
        value_template: "{{ states.zwave.nursery_window.attributes.battery_level|default(-1)|int if states.zwave.nursery_window is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      master_bedroom_window_battery:
        value_template: "{{ states.zwave.master_bedroom_window.attributes.battery_level|default(-1)|int if states.zwave.master_bedroom_window is not none }}"
        unit_of_measurement: '%'
        device_class: battery
      master_bathroom_window_battery:
        value_template: "{{ states.zwave.master_bathroom_window.attributes.battery_level|default(-1)|int if states.zwave.master_bathroom_window is not none }}"
        unit_of_measurement: '%'
        device_class: battery