################################################################
## Power and UPS
################################################################

# Default settings for apcupsd
apcupsd:
  host: a722577e-apcupsd
  
# Set up apcupsd sensors
sensor:
- platform: apcupsd
  resources:
    - linev
    - loadpct
    - status
    - timeleft
    - bcharge
 
# Automations
automation:
- alias: Power Failure Notification
  trigger:
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONBATT'
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONLINE'
  action:
    service: notify.charles
    data_template:
        title: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
        message: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
          {{ ' ' }}
          at {{now().strftime("%Y-%m-%d %l:%M:%S")}}