################################################################
## Power and UPS
################################################################

homeassistant:
  customize:
    sensor.energy_meter_power:
      friendly_name: Power Usage (all)
    sensor.energy_meter_power_2:
      friendly_name: Power Usage (Phase 1)
    sensor.energy_meter_power_3:
      friendly_name: Power Usage (Phase 2)


# Default settings for apcupsd
apcupsd:
  host: a722577e-apcupsd
  
# Set up apcupsd sensors
sensor:
- platform: apcupsd
  resources:
    - linev
    - loadpct
    - status
    - timeleft
    - bcharge
 
# Automations
automation:
- alias: Power Failure Notification
  trigger:
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONBATT'
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONLINE'
#      for:
#        minutes: 2
  action:
    service: notify.charles
    data_template:
        title: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
        message: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
          {{ ' ' }}
          at {{now().strftime("%Y-%m-%d %l:%M:%S")}}