################################################################
## Power and UPS
################################################################

homeassistant:
  customize:
    sensor.energy_meter_power_9_4:
      friendly_name: Power Usage (all)
    sensor.energy_meter_power_9_4_2:
      friendly_name: Power Usage (Phase 1)
    sensor.energy_meter_power_9_4_3:
      friendly_name: Power Usage (Phase 2)


# Default settings for apcupsd
apcupsd:
  host: localhost
  port: 3551
  
# Set up apcupsd sensors
sensor:
- platform: apcupsd
  resources:
    - linev
    - loadpct
    - status
    - timeleft
    - bcharge
    
# Groups
group:
  ups:
    name: Power/UPS Status
    entities:
      - sensor.energy_meter_power_9_4
      - sensor.ups_status
      - sensor.ups_input_voltage
      - sensor.ups_load
      - sensor.ups_battery
      - sensor.ups_time_left
 
# Automations
automation:
- alias: Power Failure Notification
  trigger:
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONBATT'
    - platform: state
      entity_id: sensor.ups_status
      to: 'ONLINE'
#      for:
#        minutes: 2
  action:
    service: notify.pb
    data_template:
        title: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
        message: >-
          {%- if trigger.to_state.state == 'ONBATT' -%}
          Power Failure
          {%- elif trigger.to_state.state == 'ONLINE' -%}
          Power Restored
          {%- endif -%}
          {{ ' ' }}
          at {{now().strftime("%Y-%m-%d %l:%M:%S")}}